#!/usr/bin/env python3
"""
Compile standalone_presets/*.json into firmware/shared_core/protocol/presets_generated.cpp.

Each preset is validated against protocols/schemas/standalone_preset.schema.json
first. The generated file is committed, so a firmware build needs no Python.
CI re-runs this script with --check and fails if the committed file is stale.

    python3 standalone_presets/compile_presets.py          # regenerate
    python3 standalone_presets/compile_presets.py --check  # CI: verify up to date
"""
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "firmware", "shared_core", "protocol", "presets_generated.cpp")
sys.path.insert(0, os.path.join(ROOT, "protocols"))
import validate  # noqa: E402

MODES = {"binaural": 0, "isochronic": 1, "monaural": 2, "bilateral": 3, "pulse": 4, "continuous": 5}
MODALITY = {"audio": 1, "photonic": 2, "haptic": 4, "coil": 8}
DEFAULT_ID = 1   # Deep Sleep Theta — the doc's reference standalone sequence


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def c_float(x):
    return "%.4ff" % float(x)


def load():
    presets = []
    for fn in sorted(glob.glob(os.path.join(HERE, "*.json"))):
        with open(fn) as f:
            p = json.load(f)
        errs = validate.validate("standalone_preset.schema.json", p)
        if errs:
            raise SystemExit("%s invalid:\n  %s" % (os.path.basename(fn), "\n  ".join(errs)))
        presets.append(p)
    ids = [p["id"] for p in presets]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate preset ids: %s" % ids)
    return presets


def render(presets):
    out = [
        "// GENERATED by standalone_presets/compile_presets.py; do not edit by hand.",
        "// Source: standalone_presets/*.json",
        '#include "preset_player.h"',
        "",
        "namespace cocoon {",
        "namespace {",
        "",
    ]
    for p in presets:
        out.append("// %s: %s" % (p["id"], p["name"]))
        out.append("const PresetStep kSteps%d[] = {" % p["id"])
        for s in p["steps"]:
            mask = 0
            for m in s["modality"]:
                mask |= MODALITY[m]
            out.append("    {%du, %du, %s, %s, %s, %s, %d, %d},%s" % (
                round(s["hold_s"] * 1000), round(s["ramp_s"] * 1000),
                c_float(s["fc"]), c_float(s["fe"]), c_float(s["amp"]), c_float(s.get("pan", 0.0)),
                MODES[s["mode"]], mask, ("  // " + s["note"]) if s.get("note") else ""))
        out.append("};")
        out.append("")
    out.append("const Preset kPresets[] = {")
    for p in presets:
        out.append("    {%d, %s, kSteps%d, sizeof(kSteps%d) / sizeof(PresetStep), %s, %s}," % (
            p["id"], c_str(p["name"]), p["id"], p["id"],
            "true" if p["loop"] else "false",
            "true" if p.get("photosensitive_consent_required") else "false"))
    out += [
        "};",
        "constexpr size_t kCount = sizeof(kPresets) / sizeof(Preset);",
        "",
        "}  // namespace",
        "",
        "const Preset* findPreset(uint16_t id) {",
        "    for (size_t i = 0; i < kCount; ++i) if (kPresets[i].id == id) return &kPresets[i];",
        "    return nullptr;",
        "}",
        "const Preset* defaultPreset() { return findPreset(%d); }" % DEFAULT_ID,
        "size_t presetCount() { return kCount; }",
        "const Preset* presetAt(size_t i) { return i < kCount ? &kPresets[i] : nullptr; }",
        "",
        "}  // namespace cocoon",
        "",
    ]
    return "\n".join(out)


def main():
    text = render(load())
    if "--check" in sys.argv:
        with open(OUT) as f:
            if f.read() != text:
                print("presets_generated.cpp is stale; run standalone_presets/compile_presets.py")
                return 1
        print("presets_generated.cpp up to date")
        return 0
    with open(OUT, "w") as f:
        f.write(text)
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
