// GENERATED by standalone_presets/compile_presets.py; do not edit by hand.
// Source: standalone_presets/*.json
#include "preset_player.h"

namespace cocoon {
namespace {

// 1: Deep Sleep Theta Protocol
const PresetStep kSteps1[] = {
    {240000u, 5000u, 432.0000f, 10.0000f, 0.3500f, 0.0000f, 1, 1},  // settle at alpha
    {300000u, 120000u, 432.0000f, 7.8300f, 0.3300f, 0.0000f, 1, 1},  // Schumann bridge
    {480000u, 180000u, 396.0000f, 6.0000f, 0.3000f, 0.0000f, 1, 1},
    {600000u, 240000u, 396.0000f, 4.0000f, 0.2600f, 0.0000f, 1, 1},  // deep theta
    {420000u, 240000u, 396.0000f, 2.0000f, 0.2000f, 0.0000f, 1, 1},  // delta, fading
    {0u, 60000u, 396.0000f, 2.0000f, 0.0000f, 0.0000f, 1, 1},  // fade out
};

// 2: Alpha Calm Focus
const PresetStep kSteps2[] = {
    {600000u, 10000u, 432.0000f, 10.0000f, 0.3500f, 0.0000f, 0, 1},
    {600000u, 60000u, 432.0000f, 10.5000f, 0.3500f, 0.0000f, 0, 1},
    {600000u, 60000u, 432.0000f, 9.5000f, 0.3500f, 0.0000f, 0, 1},
};

// 3: Gamma 40 Hz Audio-Visual
const PresetStep kSteps3[] = {
    {60000u, 10000u, 432.0000f, 40.0000f, 0.2500f, 0.0000f, 1, 3},  // introduce
    {1080000u, 30000u, 432.0000f, 40.0000f, 0.4000f, 0.0000f, 1, 3},
    {0u, 60000u, 432.0000f, 40.0000f, 0.0000f, 0.0000f, 1, 3},  // fade out
};

// 4: Schumann Grounding
const PresetStep kSteps4[] = {
    {900000u, 20000u, 432.0000f, 7.8300f, 0.3000f, 0.0000f, 1, 9},
};

// 5: Stress Downshift (HRV Recovery)
const PresetStep kSteps5[] = {
    {120000u, 5000u, 432.0000f, 10.0000f, 0.3500f, 0.0000f, 1, 1},
    {900000u, 15000u, 396.0000f, 4.0000f, 0.3000f, 0.0000f, 1, 1},  // 15 s ramp per spec
    {180000u, 60000u, 396.0000f, 6.0000f, 0.3000f, 0.0000f, 1, 1},  // gentle return
    {0u, 30000u, 396.0000f, 6.0000f, 0.0000f, 0.0000f, 1, 1},
};

// 6: Bilateral Tactile Alternation
const PresetStep kSteps6[] = {
    {30000u, 5000u, 432.0000f, 1.0000f, 0.3500f, 0.0000f, 3, 4},  // haptics first
    {270000u, 10000u, 432.0000f, 1.0000f, 0.4000f, 0.0000f, 3, 4},
    {240000u, 30000u, 432.0000f, 0.8000f, 0.4000f, 0.0000f, 3, 4},  // slow down
    {0u, 20000u, 432.0000f, 0.8000f, 0.0000f, 0.0000f, 3, 4},
};

// 7: Chakra Ascent (Solfeggio)
const PresetStep kSteps7[] = {
    {120000u, 15000u, 396.0000f, 7.8300f, 0.3000f, 0.0000f, 1, 1},  // root
    {120000u, 15000u, 417.0000f, 7.8300f, 0.3000f, 0.0000f, 1, 1},  // sacral
    {120000u, 15000u, 528.0000f, 7.8300f, 0.3000f, 0.0000f, 1, 1},  // solar plexus
    {120000u, 15000u, 639.0000f, 7.8300f, 0.3000f, 0.0000f, 1, 1},  // heart
    {120000u, 15000u, 741.0000f, 7.8300f, 0.3000f, 0.0000f, 1, 1},  // throat
    {120000u, 15000u, 852.0000f, 7.8300f, 0.3000f, 0.0000f, 1, 1},  // third eye
    {120000u, 15000u, 963.0000f, 7.8300f, 0.3000f, 0.0000f, 1, 1},  // crown
    {0u, 30000u, 963.0000f, 7.8300f, 0.0000f, 0.0000f, 1, 1},
};

const Preset kPresets[] = {
    {1, "Deep Sleep Theta Protocol", kSteps1, sizeof(kSteps1) / sizeof(PresetStep), false, false},
    {2, "Alpha Calm Focus", kSteps2, sizeof(kSteps2) / sizeof(PresetStep), true, false},
    {3, "Gamma 40 Hz Audio-Visual", kSteps3, sizeof(kSteps3) / sizeof(PresetStep), false, true},
    {4, "Schumann Grounding", kSteps4, sizeof(kSteps4) / sizeof(PresetStep), true, false},
    {5, "Stress Downshift (HRV Recovery)", kSteps5, sizeof(kSteps5) / sizeof(PresetStep), false, false},
    {6, "Bilateral Tactile Alternation", kSteps6, sizeof(kSteps6) / sizeof(PresetStep), false, false},
    {7, "Chakra Ascent (Solfeggio)", kSteps7, sizeof(kSteps7) / sizeof(PresetStep), false, false},
};
constexpr size_t kCount = sizeof(kPresets) / sizeof(Preset);

}  // namespace

const Preset* findPreset(uint16_t id) {
    for (size_t i = 0; i < kCount; ++i) if (kPresets[i].id == id) return &kPresets[i];
    return nullptr;
}
const Preset* defaultPreset() { return findPreset(1); }
size_t presetCount() { return kCount; }
const Preset* presetAt(size_t i) { return i < kCount ? &kPresets[i] : nullptr; }

}  // namespace cocoon
